### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Githubman6996** [LoganKaval/VSBAC#3]
How the fuck do you run this

**Comment by LoganKaval** [comment]
It's Not Finished. When it is You Can Run it by Running the "start.py" File. 
Yes, I Know the File that You Have to Run is Typically the "main.py" File.

**Comment by Githubman6996** [comment]
Ohhhh ok

**Comment by LoganKaval** [comment]
Next Time Please Do Not Use That Type Of Language Please.

**Comment by Githubman6996** [comment]
> Next Time Please Do Not Use That Type Of Language Please.

Sorry
